services:
  - type: web
    name: crop-disease-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -k uvicorn.workers.UvicornWorker app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
